Add PHP 8.4 support

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,7 +18,7 @@ jobs:
 
       - name: "Check if files are in-sync"
         run: |
-          rm -rf data/
+          rm -r data/
           php make.php
           git add . -N && git diff --exit-code
 
@@ -47,6 +47,9 @@ jobs:
           - "8.3-alpine"
           - "8.3-zts-alpine"
           - "8.3-debug-alpine"
+          - "8.4-alpine"
+          - "8.4-zts-alpine"
+          - "8.4-debug-alpine"
           - "7.4-debian"
           - "7.4-zts-debian"
           - "7.4-debug-debian"
@@ -62,6 +65,9 @@ jobs:
           - "8.3-debian"
           - "8.3-zts-debian"
           - "8.3-debug-debian"
+          - "8.4-debian"
+          - "8.4-zts-debian"
+          - "8.4-debug-debian"
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -343,6 +349,61 @@ jobs:
           ; fi
           && git add . -N && git diff --diff-filter=d
 
+      - name: 'Build base image - clone & patch - 8.4.x'
+        if: (matrix.imageName == '8.4-alpine' || matrix.imageName == '8.4-zts-alpine' || matrix.imageName == '8.4-debug-alpine' || matrix.imageName == '8.4-debian' || matrix.imageName == '8.4-zts-debian' || matrix.imageName == '8.4-debug-debian')
+        run: >-
+          if [ "${{ matrix.imageName }}" == "8.4-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debian" ] || [ "${{ matrix.imageName }}" == "8.4-zts-debian" ] || [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          export PHPSRC_BRANCH="$(git ls-remote 'https://github.com/php/php-src.git' | grep -iE '\srefs/heads/master$' | sort -k2 -V | tee /dev/stderr | awk 'END{print $NF}' | sed -E 's~^refs/[^/]+/~~')"
+          ; fi
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debian" ] || [ "${{ matrix.imageName }}" == "8.4-zts-debian" ] || [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          git clone --depth 1 'https://github.com/php/php-src.git' -b "$PHPSRC_BRANCH" phpsrc
+          ; fi
+          && cd phpsrc && export PHPSRC_COMMIT="$(git rev-parse HEAD)"
+          && git checkout -B master
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ]; then
+          sed -E 's~#if HAVE_OCILOBREAD2$~#if 1~' -i ext/pdo_oci/oci_statement.c && git -c user.name="a" -c user.email="a@a" commit -am "Fix pdo_oci ext NCLOB read for Alpine"
+          ; fi
+          && sudo apt-get -y update && sudo apt-get -y install bison re2c
+          && scripts/dev/makedist > /dev/null && mv php-master-*.tar.xz php.tar.xz
+          && git add . -N && git diff --diff-filter=d "$PHPSRC_COMMIT"
+          && cd ..
+          && git clone https://github.com/docker-library/php.git dlphp && cd dlphp
+          && true
+          && rm -r [0-9].[0-9]*/ && sed -E 's~( // )error\("missing GPG keys for " \+ env\.version\)~\1["x"]~' -i Dockerfile-linux.template
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ]; then
+          echo '{ "8.3-rc": { "url": "x", "variants": [ "alpine3.18/cli" ], "version": "8.3RC99" } }' > versions.json
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ]; then
+          echo '{ "8.3-rc": { "url": "x", "variants": [ "alpine3.18/zts" ], "version": "8.3RC99" } }' > versions.json
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debian" ] || [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          echo '{ "8.3-rc": { "url": "x", "variants": [ "bookworm/cli" ], "version": "8.3RC99" } }' > versions.json
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-debian" ]; then
+          echo '{ "8.3-rc": { "url": "x", "variants": [ "bookworm/zts" ], "version": "8.3RC99" } }' > versions.json
+          ; fi
+          && git apply -v ../fix-dlphp-strip-pr1280.patch
+          && ./apply-templates.sh
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ]; then
+          mv 8.3-rc/alpine3.18/cli/ img
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ]; then
+          mv 8.3-rc/alpine3.18/zts/ img
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debian" ] || [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          mv 8.3-rc/bookworm/cli/ img
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-debian" ]; then
+          mv 8.3-rc/bookworm/zts/ img
+          ; fi
+          && cd img && mv ../../phpsrc/php.tar.xz .
+          && sed -E 's~^(ENV PHP_VERSION[ =]).*~\1CUSTOM--'"$PHPSRC_BRANCH--$PHPSRC_COMMIT"'~' -i Dockerfile
+          && sed -E 's~^(ENV PHP_URL[ =]).*~COPY php.tar.xz /usr/src/~' -i Dockerfile
+          && sed -E 's~^(ENV (GPG_KEYS|PHP_URL|PHP_ASC_URL|PHP_SHA256)[ =]).*~~' -i Dockerfile
+          && sed -E 's~-n "\$(PHP_SHA256|PHP_ASC_URL)"~-n ""~' -i Dockerfile
+          && sed -E 's~curl -fsSL -o php.tar.xz .*; ~~' -i Dockerfile
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ]; then
+          sed -E 's~(--with-curl.*)( \\)~\1 --enable-embed\2~' -i Dockerfile
+          ; fi
+          && if [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ] || [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          sed -E 's~(--with-curl.*)( \\)~\1 --enable-debug\2~' -i Dockerfile
+          ; fi
+          && git add . -N && git diff --diff-filter=d
+
       - name: 'Build base image - build - 7.4.x'
         if: (matrix.imageName == '7.4-alpine' || matrix.imageName == '7.4-zts-alpine' || matrix.imageName == '7.4-debug-alpine' || matrix.imageName == '7.4-debian' || matrix.imageName == '7.4-zts-debian' || matrix.imageName == '7.4-debug-debian')
         # try to build twice to suppress random network issues with Github Actions
@@ -526,6 +587,43 @@ jobs:
           && ((docker pull "$REGISTRY_IMAGE_NAME:8.3-debug-debian-base" || docker pull "$REGISTRY_IMAGE_NAME:8.3-debug-debian-base") || true)
           && (docker build --cache-from "php:8.3-rc-cli-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.3-debug-debian-base" -t "ci-target:base" ./
           || docker build --cache-from "php:8.3-rc-cli-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.3-debug-debian-base" -t "ci-target:base" ./)
+          ; fi
+
+      - name: 'Build base image - build - 8.4.x'
+        if: (matrix.imageName == '8.4-alpine' || matrix.imageName == '8.4-zts-alpine' || matrix.imageName == '8.4-debug-alpine' || matrix.imageName == '8.4-debian' || matrix.imageName == '8.4-zts-debian' || matrix.imageName == '8.4-debug-debian')
+        # try to build twice to suppress random network issues with Github Actions
+        run: >-
+          cd dlphp/img
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ]; then
+          ((docker pull "php:8.3-rc-cli-alpine3.18" || docker pull "php:8.3-rc-cli-alpine3.18") || true)
+          && ((docker pull "$REGISTRY_IMAGE_NAME:8.4-alpine-base" || docker pull "$REGISTRY_IMAGE_NAME:8.4-alpine-base") || true)
+          && (docker build --cache-from "php:8.3-rc-cli-alpine3.18" --cache-from "$REGISTRY_IMAGE_NAME:8.4-alpine-base" -t "ci-target:base" ./
+          || docker build --cache-from "php:8.3-rc-cli-alpine3.18" --cache-from "$REGISTRY_IMAGE_NAME:8.4-alpine-base" -t "ci-target:base" ./)
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ]; then
+          ((docker pull "php:8.3-rc-zts-alpine3.18" || docker pull "php:8.3-rc-zts-alpine3.18") || true)
+          && ((docker pull "$REGISTRY_IMAGE_NAME:8.4-zts-alpine-base" || docker pull "$REGISTRY_IMAGE_NAME:8.4-zts-alpine-base") || true)
+          && (docker build --cache-from "php:8.3-rc-zts-alpine3.18" --cache-from "$REGISTRY_IMAGE_NAME:8.4-zts-alpine-base" -t "ci-target:base" ./
+          || docker build --cache-from "php:8.3-rc-zts-alpine3.18" --cache-from "$REGISTRY_IMAGE_NAME:8.4-zts-alpine-base" -t "ci-target:base" ./)
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ]; then
+          ((docker pull "php:8.3-rc-cli-alpine3.18" || docker pull "php:8.3-rc-cli-alpine3.18") || true)
+          && ((docker pull "$REGISTRY_IMAGE_NAME:8.4-debug-alpine-base" || docker pull "$REGISTRY_IMAGE_NAME:8.4-debug-alpine-base") || true)
+          && (docker build --cache-from "php:8.3-rc-cli-alpine3.18" --cache-from "$REGISTRY_IMAGE_NAME:8.4-debug-alpine-base" -t "ci-target:base" ./
+          || docker build --cache-from "php:8.3-rc-cli-alpine3.18" --cache-from "$REGISTRY_IMAGE_NAME:8.4-debug-alpine-base" -t "ci-target:base" ./)
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debian" ]; then
+          ((docker pull "php:8.3-rc-cli-bookworm" || docker pull "php:8.3-rc-cli-bookworm") || true)
+          && ((docker pull "$REGISTRY_IMAGE_NAME:8.4-debian-base" || docker pull "$REGISTRY_IMAGE_NAME:8.4-debian-base") || true)
+          && (docker build --cache-from "php:8.3-rc-cli-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.4-debian-base" -t "ci-target:base" ./
+          || docker build --cache-from "php:8.3-rc-cli-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.4-debian-base" -t "ci-target:base" ./)
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-debian" ]; then
+          ((docker pull "php:8.3-rc-zts-bookworm" || docker pull "php:8.3-rc-zts-bookworm") || true)
+          && ((docker pull "$REGISTRY_IMAGE_NAME:8.4-zts-debian-base" || docker pull "$REGISTRY_IMAGE_NAME:8.4-zts-debian-base") || true)
+          && (docker build --cache-from "php:8.3-rc-zts-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.4-zts-debian-base" -t "ci-target:base" ./
+          || docker build --cache-from "php:8.3-rc-zts-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.4-zts-debian-base" -t "ci-target:base" ./)
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          ((docker pull "php:8.3-rc-cli-bookworm" || docker pull "php:8.3-rc-cli-bookworm") || true)
+          && ((docker pull "$REGISTRY_IMAGE_NAME:8.4-debug-debian-base" || docker pull "$REGISTRY_IMAGE_NAME:8.4-debug-debian-base") || true)
+          && (docker build --cache-from "php:8.3-rc-cli-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.4-debug-debian-base" -t "ci-target:base" ./
+          || docker build --cache-from "php:8.3-rc-cli-bookworm" --cache-from "$REGISTRY_IMAGE_NAME:8.4-debug-debian-base" -t "ci-target:base" ./)
           ; fi
 
       - name: 'Target "basic" - build'
@@ -866,4 +964,52 @@ jobs:
           && dtp "basic" "8.3-debug-debian"
           && dtp "node" "8.3-debug-debian-node"
           && dtp "selenium" "8.3-debug-debian-selenium"
+          ; fi
+
+      - name: 'Push tags to registry - 8.4.x'
+        if: (github.ref == 'refs/heads/master') && (matrix.imageName == '8.4-alpine' || matrix.imageName == '8.4-zts-alpine' || matrix.imageName == '8.4-debug-alpine' || matrix.imageName == '8.4-debian' || matrix.imageName == '8.4-zts-debian' || matrix.imageName == '8.4-debug-debian')
+        run: >-
+          dtp() { docker tag "ci-target:$1" "$REGISTRY_IMAGE_NAME:$2" && docker push "$REGISTRY_IMAGE_NAME:$2"; }
+          && if [ "${{ matrix.imageName }}" == "8.4-alpine" ]; then
+          dtp "base" "8.4-base"
+          && dtp "base" "8.4-alpine-base"
+          && dtp "basic" "8.4"
+          && dtp "basic" "8.4-alpine"
+          && dtp "node" "8.4-node"
+          && dtp "node" "8.4-alpine-node"
+          && dtp "selenium" "8.4-selenium"
+          && dtp "selenium" "8.4-alpine-selenium"
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-alpine" ]; then
+          dtp "base" "8.4-zts-base"
+          && dtp "base" "8.4-zts-alpine-base"
+          && dtp "basic" "8.4-zts"
+          && dtp "basic" "8.4-zts-alpine"
+          && dtp "node" "8.4-zts-node"
+          && dtp "node" "8.4-zts-alpine-node"
+          && dtp "selenium" "8.4-zts-selenium"
+          && dtp "selenium" "8.4-zts-alpine-selenium"
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debug-alpine" ]; then
+          dtp "base" "8.4-debug-base"
+          && dtp "base" "8.4-debug-alpine-base"
+          && dtp "basic" "8.4-debug"
+          && dtp "basic" "8.4-debug-alpine"
+          && dtp "node" "8.4-debug-node"
+          && dtp "node" "8.4-debug-alpine-node"
+          && dtp "selenium" "8.4-debug-selenium"
+          && dtp "selenium" "8.4-debug-alpine-selenium"
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debian" ]; then
+          dtp "base" "8.4-debian-base"
+          && dtp "basic" "8.4-debian"
+          && dtp "node" "8.4-debian-node"
+          && dtp "selenium" "8.4-debian-selenium"
+          ; elif [ "${{ matrix.imageName }}" == "8.4-zts-debian" ]; then
+          dtp "base" "8.4-zts-debian-base"
+          && dtp "basic" "8.4-zts-debian"
+          && dtp "node" "8.4-zts-debian-node"
+          && dtp "selenium" "8.4-zts-debian-selenium"
+          ; elif [ "${{ matrix.imageName }}" == "8.4-debug-debian" ]; then
+          dtp "base" "8.4-debug-debian-base"
+          && dtp "basic" "8.4-debug-debian"
+          && dtp "node" "8.4-debug-debian-node"
+          && dtp "selenium" "8.4-debug-debian-selenium"
           ; fi
